# Generated by Django 3.2.6 on 2021-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_title', models.CharField(max_length=200)),
                ('material_detail', models.CharField(max_length=500)),
                ('uploaded_time', models.CharField(max_length=50)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploader_course', models.CharField(max_length=100)),
                ('uploader_sem', models.CharField(max_length=20)),
            ],
        ),
    ]
