# Generated by Django 3.2.6 on 2021-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='uploader_file',
            field=models.FileField(default='', upload_to='static/'),
        ),
    ]
