# Generated by Django 3.2.6 on 2022-01-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211111_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='uploader_file',
            new_name='upload_file',
        ),
    ]
