# Generated by Django 4.0.1 on 2022-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_uploader_file_studymaterial_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uploaded_time', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=200)),
                ('likes', models.IntegerField(max_length=5)),
                ('desc', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
