# Generated by Django 4.0.1 on 2022-01-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_data',
            name='userprofile',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
