# Generated by Django 4.0.1 on 2022-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_post_data_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_data',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
